# Generated by Django 5.2.11 on 2026-10-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0009_favorite_created_at_favorite_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=253, unique=True)),
                ("data", models.BinaryField(blank=True, default=b"")),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("found", models.BooleanField(default=False)),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "db_table": "app_site_icon",
            },
        ),
    ]
