# Generated by Django 5.2.11 on 2026-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_task_reminder_sent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=1),
        ),
    ]
