# Generated by Django 5.2.11 on 2026-10-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="time_zone",
            field=models.CharField(default="America/New_York", max_length=64),
        ),
        migrations.CreateModel(
            name="TaskReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("minutes", "minutes"),
                            ("hours", "hours"),
                            ("days", "days"),
                            ("weeks", "weeks"),
                        ],
                        default="minutes",
                        max_length=10,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("sent_for", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "app_task_reminder",
                "ordering": ["-unit", "-amount"],
                "abstract": False,
            },
        ),
    ]
