# Generated by Django 5.2.11 on 2026-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_task_time_zone_and_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=5),
        ),
    ]
