# Generated by Django 5.2.11 on 2026-10-07 12:50

from datetime import timedelta

from django.db import migrations, models


def _first_on_or_after(base, test, limit=1500):
    """The first day on or after a day that passes a test."""
    for offset in range(limit):
        day = base + timedelta(days=offset)
        if test(day):
            return day
    return base


def convert_rules(apps, schema_editor):
    """The old rule (a type, a day of the week or month, a month) becomes
    the shared rule: a frequency counted from a start day on which the old
    rule falls, so the same days come round. The start is the template's due
    date where that fits, or the next day on or after it that does."""
    Task = apps.get_model("tasks", "Task")
    for template in Task.objects.filter(is_recurring=True):
        kind = template.recurrence_type
        if kind not in ("daily", "weekly", "monthly", "yearly"):
            template.is_recurring = False
            template.save(update_fields=["is_recurring"])
            continue
        base = template.due_date or template.created_at.date()
        day, month = template.recurrence_day, template.recurrence_month
        template.repeat_frequency = kind
        template.repeat_interval = 1
        template.repeat_monthly_by = "day"
        if kind == "daily":
            start = base
        elif kind == "weekly":
            weekday = day if day is not None else base.weekday()
            template.repeat_weekdays = str(weekday)
            start = _first_on_or_after(base, lambda d: d.weekday() == weekday)
        elif kind == "monthly":
            wanted = day or base.day
            start = _first_on_or_after(base, lambda d: d.day == wanted)
        else:
            wanted_day, wanted_month = day or base.day, month or base.month
            start = _first_on_or_after(
                base, lambda d: d.day == wanted_day and d.month == wanted_month
            )
        template.repeat_start = start
        template.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_task_priority_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="repeat_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_interval",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_monthly_by",
            field=models.CharField(
                choices=[("day", "Day of the month"), ("weekday", "Weekday")],
                default="day",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_weekdays",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(convert_rules, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="task",
            name="recurrence_day",
        ),
        migrations.RemoveField(
            model_name="task",
            name="recurrence_month",
        ),
        migrations.RemoveField(
            model_name="task",
            name="recurrence_type",
        ),
    ]
