# Generated by Django 5.2.11 on 2026-10-08 17:07

from django.db import migrations, models


def channel_from_user(apps, schema_editor):
    """A notification set before there were channels goes the way its
    user had chosen for all of them."""
    TaskReminder = apps.get_model("tasks", "TaskReminder")
    for choice in ("ntfy",):
        TaskReminder.objects.filter(task__user__notify_by=choice).update(channel=choice)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_repeat_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskreminder",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("ntfy", "Push"), ("home", "Homepage")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.RunPython(channel_from_user, migrations.RunPython.noop),
    ]
