# Generated by Django 5.2.11 on 2026-10-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_notification_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_sent_date',
        ),
    ]
