# Generated by Django 5.2.11 on 2026-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_customuser_notification_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="task_completion_mode",
            field=models.CharField(
                choices=[
                    ("complete", "Mark complete"),
                    ("archive", "Auto-archive"),
                    ("delete", "Auto-delete"),
                ],
                default="complete",
                max_length=10,
            ),
        ),
    ]
