# Generated by Django 5.2.11 on 2026-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_customuser_managers_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_weather",
            field=models.IntegerField(default=0),
        ),
    ]
