# Generated by Django 5.2.11 on 2026-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_add_home_weather"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="weather_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weather_lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
