# Generated by Django 5.2.11 on 2026-03-22 15:28

from django.db import migrations, models


def enable_home_weather(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    CustomUser.objects.filter(home_weather=0).update(home_weather=1)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_add_weather_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="home_weather",
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(enable_home_weather, migrations.RunPython.noop),
    ]
