# Generated by Django 5.2.11 on 2026-10-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_default_home_weather_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="calendar_sync",
            field=models.BooleanField(default=False),
        ),
    ]
