# Generated by Django 5.2.11 on 2026-10-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_customuser_calendar_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="calendar_forward_from",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="calendar_inbound_token",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
