# Generated by Django 5.2.11 on 2026-10-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_customuser_calendar_forward_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="time_zone",
            field=models.CharField(default="America/New_York", max_length=64),
        ),
    ]
