# Generated by Django 5.2.11 on 2026-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notify_by",
            field=models.CharField(
                choices=[("email", "Email"), ("ntfy", "ntfy")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ntfy_server",
            field=models.URLField(default="https://ntfy.sh"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ntfy_token",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ntfy_topic",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
