# Generated by Django 5.2.11 on 2026-10-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_notify_by_ntfy"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("last_failure", models.DateTimeField()),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
