# Generated by Django 5.2.11 on 2026-10-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_totp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="theme",
        ),
    ]
