# Generated by Django 5.2.11 on 2026-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_sign_in_by_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sessions_ended",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
