# Generated by Django 5.2.11 on 2026-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_sessions_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nav_icon",
            field=models.CharField(
                choices=[
                    ("user", "Person"),
                    ("chess-king", "King"),
                    ("chess-queen", "Queen"),
                    ("chess-rook", "Rook"),
                    ("chess-bishop", "Bishop"),
                    ("chess-knight", "Knight"),
                    ("chess-pawn", "Pawn"),
                    ("hamburger", "Hamburger"),
                    ("toolbox", "Toolbox"),
                    ("smile", "Smile"),
                    ("laugh", "Laugh"),
                    ("face-grinning", "Grin"),
                    ("meh", "Meh"),
                    ("annoyed", "Annoyed"),
                    ("frown", "Frown"),
                    ("face-slightly-frowning", "Slight frown"),
                    ("angry", "Angry"),
                    ("face-angry", "Cross"),
                    ("cat", "Cat"),
                    ("dog", "Dog"),
                    ("rabbit", "Rabbit"),
                    ("squirrel", "Squirrel"),
                    ("panda", "Panda"),
                    ("turtle", "Turtle"),
                    ("feather", "Feather"),
                    ("bird", "Bird"),
                    ("birdhouse", "Birdhouse"),
                    ("rat", "Rat"),
                    ("origami", "Origami"),
                    ("rose", "Rose"),
                    ("snail", "Snail"),
                ],
                default="user",
                max_length=40,
            ),
        ),
    ]
