# Generated by Django 5.2.11 on 2026-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_nav_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nav_icon",
            field=models.CharField(
                choices=[
                    ("user", "Person"),
                    ("chess-king", "King"),
                    ("chess-queen", "Queen"),
                    ("chess-rook", "Rook"),
                    ("chess-bishop", "Bishop"),
                    ("chess-knight", "Knight"),
                    ("chess-pawn", "Pawn"),
                    ("hamburger", "Hamburger"),
                    ("toolbox", "Toolbox"),
                    ("smile", "Smile"),
                    ("laugh", "Laugh"),
                    ("cat", "Cat"),
                    ("dog", "Dog"),
                    ("rabbit", "Rabbit"),
                    ("squirrel", "Squirrel"),
                    ("panda", "Panda"),
                    ("turtle", "Turtle"),
                    ("feather", "Feather"),
                    ("bird", "Bird"),
                    ("birdhouse", "Birdhouse"),
                    ("rat", "Rat"),
                    ("origami", "Origami"),
                    ("rose", "Rose"),
                    ("snail", "Snail"),
                ],
                default="user",
                max_length=40,
            ),
        ),
    ]
