# Generated by Django 5.2.11 on 2026-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_fewer_nav_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_quotes",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_quotes_hidden",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="quotes_cursor",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="quotes_cursor_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="quotes_mode",
            field=models.CharField(default="random", max_length=10),
        ),
    ]
