# Generated by Django 5.2.11 on 2026-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_quote_of_the_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="notify_by",
            field=models.CharField(
                choices=[("email", "Email"), ("ntfy", "Push"), ("home", "Homepage")],
                default="email",
                max_length=10,
            ),
        ),
    ]
