# Generated by Django 5.2.11 on 2026-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_notification_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="kosmos_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="customuser",
            name="kosmos_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
