# Generated by Django 5.2.11 on 2026-10-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_kosmos"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_icons",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_icons_muted",
            field=models.IntegerField(default=1),
        ),
    ]
