# Generated by Django 5.2.11 on 2026-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_home_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="encryption_iterations",
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
