# Generated by Django 5.2.11 on 2026-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_encryption_iterations"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="encryption_by_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="encryption_recovery_salt",
            field=models.CharField(blank=True, default="", max_length=44),
        ),
        migrations.AddField(
            model_name="customuser",
            name="encryption_recovery_wrapped_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="encryption_wrapped_key",
            field=models.TextField(blank=True, default=""),
        ),
    ]
