# Generated by Django 5.2.11 on 2026-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_encryption_sealed_key"),
    ]

    def turn_on(apps, schema_editor):
        apps.get_model("accounts", "CustomUser").objects.update(encryption_by_default=True)

    operations = [
        migrations.RunPython(turn_on, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customuser",
            name="encryption_by_default",
            field=models.BooleanField(default=True),
        ),
    ]
