# Generated by Django 5.2.11 on 2026-10-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_encryption_by_default_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_reminders',
        ),
    ]
