# Generated by Django 5.2.11 on 2026-10-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_weather_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="weather_dismissed_alerts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
