# Generated by Django 5.2.11 on 2026-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_weather_dismissed_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="weather_units",
            field=models.CharField(default="imperial", max_length=8),
        ),
    ]
