# Generated by Django 5.2.11 on 2026-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_home_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenotice',
            name='kind',
            field=models.CharField(choices=[('task', 'Task'), ('event', 'Event')], max_length=10),
        ),
    ]
