"""
Django settings for config project.

Generated by "django-admin startproject" using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.forms.renderers import TemplatesSetting

# Initialize environ
env = environ.Env(
    # Set casting and default values
    DEBUG=(bool, False),
    ZIP_PRIMARY=(int, 30360),
    ZIP_SECONDARY=(int, 30533),
)

# Read .env file
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Site settings
SITE_NAME = env("SITE_NAME")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# check dev v. production environment
ENV = env("ENV")

# Notifications from a machine that is not production (the dev machine,
# whose data is refreshed from production's, users' settings and all) must
# never land where production's do. So by default dev pushes to each ntfy
# topic with a suffix (a channel of its own), marks its titles, and sends
# no notification email. Each can be set in .env.
NOT_PRODUCTION = ENV != "prod"
NTFY_TOPIC_SUFFIX = env("NTFY_TOPIC_SUFFIX", default="-dev" if NOT_PRODUCTION else "")
NOTIFY_TITLE_PREFIX = env(
    "NOTIFY_TITLE_PREFIX", default="[dev] " if NOT_PRODUCTION else ""
)
EMAIL_NOTIFICATIONS = env.bool("EMAIL_NOTIFICATIONS", default=not NOT_PRODUCTION)

# urls to which the application will respond
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
# The site's address, for links in notifications sent from the background
# worker (which has no request to read it from): the first allowed host,
# unless SITE_URL says otherwise
SITE_URL = env(
    "SITE_URL", default=f"https://{ALLOWED_HOSTS[0]}" if ALLOWED_HOSTS else ""
).rstrip("/")

# trusted origins for CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://cloudportal.link",
    "https://cloud.dev-server.io",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.forms",
    "watson",
    "mathfilters",
    "django_filters",
    "django_q",
    "accounts",
    "apps.calendar",
    "apps.folders",
    "apps.home",
    "apps.favorites",
    "apps.tasks",
    "apps.contacts",
    "apps.finance",
    "apps.lab",
    "apps.management",
    "apps.notes",
    "apps.quotes",
    "apps.search",
    "apps.settings",
]

# Django-Q2: the background worker that runs the scheduled jobs (see
# apps/management/schedules.py). The database is the broker, so it needs
# nothing beyond `manage.py qcluster` running beside the web server.
Q_CLUSTER = {
    "name": "cpl",
    "workers": 2,
    "recycle": 500,
    "timeout": 300,
    # Must exceed the timeout, or a slow job is started again while it runs
    "retry": 600,
    # A job that can never succeed stops after this many attempts instead
    # of retrying forever and filling the task history
    "max_attempts": 10,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    # A job missed while the worker was down runs once at its next slot,
    # not once for every slot it missed
    "catch_up": False,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.common.BrokenLinkEmailsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Temporarily disabled for extension development
]

ROOT_URLCONF = "config.urls"

default_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

cached_loaders = [("django.template.loaders.cached.Loader", default_loaders)]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("templates"))],
        # 'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context.env",
                "config.context.site_handle",
                "config.context.theme",
            ],
            "loaders": default_loaders if DEBUG else cached_loaders,
            "libraries": {
                "cache_buster": "apps.management.templatetags.cache_buster",
            },
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": "localhost",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [str(BASE_DIR.joinpath("static"))]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.CustomUser"

# Sign-in is by email (accounts.backends); Django's own backend stays
# behind it for signing in by username in code
AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

INTERNAL_IPS = [
    "127.0.0.1",
]


# Email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_USE_TLS = True
# Mailgun also listens on 2525, for a machine whose way out on 587 is shut
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
# A mail server that does not answer fails the send in seconds rather
# than holding a request until gunicorn kills it
EMAIL_TIMEOUT = 10
SERVER_EMAIL = env("SERVER_EMAIL")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=SERVER_EMAIL)
ADMINS = [(env("ADMINS_NAME"), env("ADMINS_EMAIL"))]

# API Keys
OPEN_WEATHER_API_KEY = env("OPEN_WEATHER_API_KEY")
CRYPTO_API_KEY = env("CRYPTO_API_KEY")
ALPHAVANTAGE_STOCKS_API_KEY = env("ALPHAVANGAGE_STOCKS_API_KEY")
FINNHUB_API_KEY = env("FINNHUB_API_KEY")

# Location Settings
ZIP_PRIMARY = env("ZIP_PRIMARY")
ZIP_SECONDARY = env("ZIP_SECONDARY")

# Financial Symbols
CRYPTO_SYMBOLS = env("CRYPTO_SYMBOLS")
SECURITIES_ASSET_LIST = [
    {
        "symbol": "GME",
        "exchange": "NYSE",
        "name": "Gamestop",
    },
    {
        "symbol": "TSLA",
        "exchange": "NASDAQ",
        "name": "Tesla",
    },
    {
        "symbol": "TLRY",
        "exchange": "NASDAQ",
        "name": "Tilray",
    },
    {
        "symbol": "SNDL",
        "exchange": "NASDAQ",
        "name": "Sundial",
    },
    {
        "symbol": "BBBY",
        "exchange": "NASDAQ",
        "name": "BBBY",
    },
    {
        "symbol": "O",
        "exchange": "NYSE",
        "name": "REIT",
    },
    {
        "symbol": "FXF",
        "exchange": "NYSEARCA",
        "name": "Swiss Francs",
    },
    {
        "symbol": "GLD",
        "exchange": "NSEARCA",
        "name": "Gold ETF",
    },
    {
        "symbol": "QQQ",
        "exchange": "NASDAQ",
        "name": "Invesco Tech",
    },
    {
        "symbol": "VTV",
        "exchange": "NYSEARCA",
        "name": "Vanguard Value",
    },
]

# Test email recipient
TEST_EMAIL_RECIPIENT = [env("TEST_EMAIL_RECIPIENT")]

# Twilio SMS Settings
TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN", default="")
TWILIO_PHONE_NUMBER = env("TWILIO_PHONE_NUMBER", default="")
SMS_RECIPIENT = env("SMS_RECIPIENT", default="")


# Forwarded calendar invitations arrive through a Mailgun inbound route:
# the domain the forwarding addresses are on (post-<token>@<domain>), and
# the key Mailgun signs its webhook posts with. Both empty means the
# feature is off.
CALENDAR_INBOUND_DOMAIN = env("CALENDAR_INBOUND_DOMAIN", default="")
MAILGUN_WEBHOOK_SIGNING_KEY = env("MAILGUN_WEBHOOK_SIGNING_KEY", default="")

# set cookies (sessions) to last for two months
# default is two weeks, multiplying by four to get two months
SESSION_COOKIE_AGE = 1209600 * 4

SESSION_SAVE_EVERY_REQUEST = True


class CustomFormRenderer(TemplatesSetting):
    form_template_name = "components/form-fields.html"
    label_suffix = ""


FORM_RENDERER = "config.settings.CustomFormRenderer"

# Logging — standardized across all apps; logs live in <app>/logs/
(BASE_DIR / "logs").mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "verbose",
        },
        "null": {"class": "logging.NullHandler"},
    },
    "root": {"handlers": ["console", "file"], "level": "WARNING"},
    "loggers": {
        # Bot-driven bad Host headers are benign; drop them instead of dumping a
        # full traceback per hit (this was chf's 117 MB error-log flood).
        "django.security.DisallowedHost": {"handlers": ["null"], "propagate": False},
    },
}
