# Generated by Django 5.2.11 on 2026-10-06 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0002_event_end_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ical_sequence",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="ical_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["user", "ical_uid"], name="app_event_user_id_9196d1_idx"
            ),
        ),
    ]
