# Generated by Django 5.2.11 on 2026-10-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0003_event_ical_sequence_event_ical_uid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("minutes", "minutes"),
                            ("hours", "hours"),
                            ("days", "days"),
                            ("weeks", "weeks"),
                        ],
                        default="minutes",
                        max_length=10,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("sent_for", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="calendar.event",
                    ),
                ),
            ],
            options={
                "db_table": "app_event_reminder",
                "ordering": ["-unit", "-amount"],
            },
        ),
    ]
