# Generated by Django 5.2.11 on 2026-10-07 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0005_time_zone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("weekdays", models.CharField(blank=True, max_length=20)),
                (
                    "monthly_by",
                    models.CharField(
                        choices=[("day", "Day of the month"), ("weekday", "Weekday")],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("start", models.DateField()),
                ("until", models.DateField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
                ("generated_through", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("span_days", models.PositiveIntegerField(default=0)),
                (
                    "time_zone",
                    models.CharField(default="America/New_York", max_length=64),
                ),
                ("event_type", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                ("reminders", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_event_series",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="calendar.eventseries",
            ),
        ),
    ]
