# Generated by Django 5.2.11 on 2026-10-07 12:26

from django.db import migrations
from django.db.models import Q


def keep_types_as_locations(apps, schema_editor):
    """An event's type (Zoom, Phone, ...) goes into its location where the
    location is empty, so nothing that was entered is lost with the column.
    Where both are set, the location already says where it is."""
    for name in ("Event", "EventSeries"):
        model = apps.get_model("calendar", name)
        for row in model.objects.exclude(Q(event_type__isnull=True) | Q(event_type="")).filter(
            Q(location__isnull=True) | Q(location="")
        ):
            row.location = row.event_type
            row.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0006_event_series"),
    ]

    operations = [
        migrations.RunPython(keep_types_as_locations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="event",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="eventseries",
            name="event_type",
        ),
    ]
