# Generated by Django 5.2.11 on 2026-10-08 17:07

from django.db import migrations, models


def channel_from_user(apps, schema_editor):
    """A notification set before there were channels goes the way its
    user had chosen for all of them; a series' template notifications
    (the ones its later occurrences are given) likewise."""
    EventReminder = apps.get_model("calendar", "EventReminder")
    EventSeries = apps.get_model("calendar", "EventSeries")
    for choice in ("ntfy",):
        EventReminder.objects.filter(event__user__notify_by=choice).update(
            channel=choice
        )
    for series in EventSeries.objects.exclude(reminders=[]).select_related("user"):
        series.reminders = [
            {"channel": series.user.notify_by, **item} for item in series.reminders
        ]
        series.save(update_fields=["reminders"])


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0007_remove_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreminder",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("ntfy", "Push"), ("home", "Homepage")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.RunPython(channel_from_user, migrations.RunPython.noop),
    ]
