# Generated by Django 5.2.11 on 2026-10-08 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0008_notification_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="invite_sequence",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="invite_uid",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="EventGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs-action", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("tentative", "Maybe"),
                        ],
                        default="needs-action",
                        max_length=12,
                    ),
                ),
                ("invited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="calendar.event",
                    ),
                ),
            ],
            options={
                "db_table": "app_event_guest",
                "ordering": ["invited_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "email"), name="guest_once"
                    )
                ],
            },
        ),
    ]
